version: '3.3'

services:
  db:
    image: postgres
  django:
    build:
      context: ./backend
      args:
        mode: dev
    command: sh -c "python manage.py collectstatic --noinput; gunicorn config.wsgi:application --name dms --bind 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.prod
    volumes:
      - ./backend:/code
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
  ssl-proxy:
    build: ./ssl-dev
    ports:
      - "443:443"
    depends_on:
      - django

