version: '3.3'

services:
  db:
    image: postgres
  frontend:
    build:
      context: ./frontend
    command: npm run-script develop
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
  django:
    build:
      context: ./backend
      args:
        mode: dev
    command: python3 manage.py runserver 0.0.0.0:80
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.dev
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db
  ssl-proxy:
    build: ./ssl-dev
    ports:
      - "443:443"
    depends_on:
      - django

