version: '3.3'

services:
  db:
    image: postgres
  django:
    build:
      context: ./backend
      args:
        mode: dev
    command: python3 manage.py runserver 0.0.0.0:80
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.dev
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        mode: dev
    command: npm run start
    volumes:
      - ./frontend:/home/app/frontend
      - /home/app/frontend/node_modules
  ssl-proxy:
    build: ./ssl-dev
    ports:
      - "443:443"
    depends_on:
      - django

